# Generated by Django 3.1.5 on 2021-01-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('con_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('ph_no', models.CharField(default='', max_length=50)),
                ('comments', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
