# Generated by Django 3.1.5 on 2021-01-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allPosts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_thumbnail', models.ImageField(upload_to='images/post_img')),
                ('title', models.CharField(default='', max_length=500)),
                ('contents', models.CharField(default='', max_length=100000)),
                ('author_of_post', models.CharField(default='', max_length=500)),
                ('time', models.DateTimeField(blank=True)),
            ],
        ),
    ]
