# Generated by Django 3.1.5 on 2021-02-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_allposts_releated_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allposts',
            name='releated_to',
        ),
    ]
