# Generated by Django 3.1.6 on 2021-02-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_allposts_releated_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allposts',
            name='contents',
            field=models.CharField(default='', max_length=10000000),
        ),
    ]
